module.exports = {
  collection: [
    '🔎 *looking around...*',
    '🧲 *attracting results...*',
    '📡 *contacting nasa...*',
    '📻 *analyzing airwaves...*',
    '📞 *making a call...*',
    '🔮 *looking into the future*',
    '🔦 *checking in all the scary spots...*',
    "⏱ *taking as long as I heckin' want...*",
    '🔬 *researching...*',
    '📠 *faxing your mom...*',
    '🧭 *getting bearings*',
    '🔭 *gazing into the vacuum of space...*',
    '🛒 *shopping for data...*',
    '🔑 *where did I put my keys...*',
    '📫 *snail-mail might be faster...*',
    '👉👌 *poking around...*',
    '🧠 *big brain time...*',
    '🐌 *brb...*',
    '🚀 *blasting off again!*',
    '💤 *snoozing...*',
    '493111353385680926 *doing science...*'
  ],
}
